config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_like',      to: 'posts#like',   as: 'p_like'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  delete 'pic1_delete/:id',    to: 'posts#pic_des1', as: 'pic1_des'
  delete 'pic2_delete/:id',    to: 'posts#pic_des2', as: 'pic2_des'
  delete 'pic3_delete/:id',    to: 'posts#pic_des3', as: 'pic3_des'
  delete 'pic4_delete/:id',    to: 'posts#pic_des4', as: 'pic4_des'
  delete 'pic5_delete/:id',    to: 'posts#pic_des5', as: 'pic5_des'
  delete 'mov_delete/:id',     to: 'posts#mov_des',  as: 'mov_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  delete 'comment_delete/:id',    to: 'comments#destroy', as: 'com_des'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  delete 'reply_delete/:id',    to: 'replies#destroy', as: 'rep_des'
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',  to: 'users#show',   as: 'u_show'
  get  'user/status/:id',    to: 'users#status',  as: 'u_sts'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get    '/login',         to: 'sessions#new',       as: 'login'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/edit',          to: 'sessions#edit',      as: 're_log'
  patch  '/update/login',        to: 'sessions#update',    as: 'log_upd'

  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  delete 'room_delete/:id',            to: 'rooms#destroy', as: 'room_des'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
  delete 'message_delete/:id',         to: 'messages#destroy', as: 'mes_des'
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'result', to: 'search#result'
  
  resources :notifications, only: :index
  
  delete 'user_delete/:id', to: 'users#destroy', as: 'u_des'
  
  get  'consultation',      to: 'consultations#new',   as: 'consultation'
  post 'consultation_send', to: 'consultations#create',  as: 'cons_create'
  get  'acceptance',        to: 'consultations#accep', as: 'accep'
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :notifications, dependent: :destroy
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  belongs_to :room
  
  def save_notification_message!(sender_id, receiver_id, message_id)
    notification = sender.active_notifications.new(
      visitor_id: sender_id,
      visited_id: receiver_id,
      message_id: message_id,
      action: 'message'
    )
    
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def sending
    @sender = current_user
    @receiver = User.find_by(id: params[:receiver_id])
    if params[:message][:room_id]
      @exist_room = Room.find_by(id: params[:message][:room_id])
      @message = @exist_room.messages.build(message_params)
      @message.sender_id = current_user.id
      if @message.sender_id == @exist_room.sender_id
        @message.receiver_id = @exist_room.receiver_id
      else
        @message.receiver_id = @exist_room.sender_id
      end
    else
      @exist_room = room_check(params[:message][:sender_id], params[:message][:receiver_id])
      if !@exist_room
        @room = Room.create(rooms_params)
      end
      @message = Message.new(message_params)
      @message.room_id = @room.id
    end
    if @message.save
      p @message
      p '1==='
      if params[:message][:room_id]
        @message.save_notification_message!(@message.sender_id, @message.receiver_id, @message.id)
      else
        if current_user.id == @message.sender.id
          @mes_receiver =  @message.receiver
        else
          @mes_receiver =  @message.sender
        end
        p current_user.id
        p @mes_receiver.id
        p @message.id
        @message.save_notification_message!(@message.sender.id, @mes_receiver.id, @message.id)
      end
      flash[:notice] = "メッセージを送信しました！"
      if @exist_room
        redirect_to exist_room_path(@exist_room.id)
      else
        redirect_to exist_room_path(@room.id)
      end
    else
      flash[:alert] = "メッセージを送信できませんでした"
      render "rooms/chat"
    end
  end
  
  def destroy
    p params
    message = Message.find_by(id: params[:id])
    message.destroy
    flash[:success] = "メッセージを削除しました"
    redirect_back(fallback_location: root_path)
  end
    
  private
    def message_params
      params.require(:message).permit(:content, :sender_id, :receiver_id, :room_id)
    end
    
    def rooms_params
      params.require(:message).permit(:sender_id, :receiver_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<h1>メッセージルーム</h1>
  <h2>ユーザー検索</h2>
    <%= form_with url: m_index_path, method: :get, local: true do |f| %>
      <%= f.text_field :nickname %>
      <%= f.submit :search %>
    <% end %>
    <table>
      <thead>
        <tr>
          <th>検索結果</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to(user.nickname, room_path(user_id: current_user.id, to_user_id: user.id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
 
 <h2>メッセージ履歴</h2>
 
   
  <% @message_user_ids.each do |message_user_id|
    message_user = User.find_by(id: message_user_id)  %>
      <% if message_user.presence %>
        <a href="/messages/room/<%= current_user.id %>/<%= message_user.id %>">
          <div class="border-b border-gray-200 flex py-4 bg-white items-center">
            <div class="w-10 h-10 mr-4">
            </div>
            <div class="">
              <a href="/messages/room/<%= current_user.id %>/<%= message_user.id %>">
              <!--<img src='/app/assets/images/rails.png', class="object-cover rounded-full h-10 w-10"/>-->
              <% if message_user.profile_image? %>
                <%= image_tag message_user.profile_image.url, class: "icon_size" %>
              <% else %>
                <i class="fas fa-user fa-3x"></i>
              <% end %>
              <%= message_user.nickname %>
              </a>
            </div>
          </div>
      <% else %>
        メッセージを行っているユーザーがいません　
    <% end %>
  <% end %>

app/views/messages/roomshow.html.erb
<h1><%= @to_user.nickname %>さんとのメッセージページ</h1>

<% if @messages.any? %>
  <% @user.messages.each do |message| %>
    <div class="right">
      <% if @user.profile_image? %>
        <%= image_tag @user.profile_image.url, class: "icon_size" %>
      <% else %>
        <i class="fas fa-user fa-3x"></i>
      <% end %>
      <%= @user.nickname %>
      <br>
      <%= message.content %>
      <br>
      <%= message.created_at%>
    </div>
      <% @to_user.messages.each do |re_message| %>
        <div class="left">
          <% if @to_user.profile_image? %>
            <%= image_tag @to_user.profile_image.url, class: "icon_size" %>
          <% else %>
            <i class="fas fa-user fa-3x"></i>
          <% end %>
          <%= @to_user.nickname %>
          <br>
          <%= re_message.content %>
          <br>
          <%= re_message.created_at%>
        </div>
      <% end %>
  <% end %>
<% end %>

  <%= form_for(@message, url: send_path) do |form| %>
    <%= form.text_area :content, id: "content", rows: "4", class: "form_textarea mb-4" %>
    <%= form.text_field :user_id, class: "hidden hide", value: current_user.id %>
    <%= form.text_field :to_user_id, class: "hidden hide", value: @to_user.id %>
    <%= form.submit "メッセージ送信", class: "btn_01" %>
  <% end %>
    
    