config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_like',      to: 'posts#like',   as: 'p_like'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  delete 'pic1_delete/:id',    to: 'posts#pic_des1', as: 'pic1_des'
  delete 'pic2_delete/:id',    to: 'posts#pic_des2', as: 'pic2_des'
  delete 'pic3_delete/:id',    to: 'posts#pic_des3', as: 'pic3_des'
  delete 'pic4_delete/:id',    to: 'posts#pic_des4', as: 'pic4_des'
  delete 'pic5_delete/:id',    to: 'posts#pic_des5', as: 'pic5_des'
  delete 'mov_delete/:id',     to: 'posts#mov_des',  as: 'mov_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  delete 'comment_delete/:id',    to: 'comments#destroy', as: 'com_des'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  delete 'reply_delete/:id',    to: 'replies#destroy', as: 'rep_des'
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',  to: 'users#show',   as: 'u_show'
  get  'user/status/:id',    to: 'users#status',  as: 'u_sts'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get    '/login',         to: 'sessions#new',       as: 'login'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/edit',          to: 'sessions#edit',      as: 're_log'
  patch  '/update/login',        to: 'sessions#update',    as: 'log_upd'

  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  delete 'room_delete/:id',            to: 'rooms#destroy', as: 'room_des'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
  delete 'message_delete/:id',         to: 'messages#destroy', as: 'mes_des'
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'result', to: 'search#result'
  
  resources :notifications, only: :index
  
  delete 'user_delete/:id', to: 'users#destroy', as: 'u_des'
  
  get  'consultation',      to: 'consultations#new',   as: 'consultation'
  post 'consultation_send', to: 'consultations#create',  as: 'cons_create'
  get  'acceptance',        to: 'consultations#accep', as: 'accep'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # has_many :rooms, dependent: :destroy
  has_many :sender, class_name: "Room", foreign_key: "sender_id", dependent: :destroy
  has_many :receiver, class_name: "Room", foreign_key: "receiver_id", dependent: :destroy
  has_many :sender, class_name: "Message", foreign_key: "sender_id", dependent: :destroy
  has_many :receiver, class_name: "Message", foreign_key: "receiver_id", dependent: :destroy
  # has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies, class_name: 'Reply', foreign_key: :user_id, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :sender, class_name: "Consultation", foreign_key: "sender_id", dependent: :destroy
  has_many :receiver, class_name: "Consultation", foreign_key: "receiver_id", dependent: :destroy
  attr_accessor :remember_token
  
  validates :nickname, presence: true, length: { maximum: 30 },
                       uniqueness: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :prefucture, presence: true
  validates :city, presence: true
  validates :classification, presence: true
  validates :nursing, presence: true
  validates :key_word1, presence: { message: 'は１つは入力してください。' }
  validates :answer_digest, presence: true
  
  mount_uploader :profile_image, ProfileImageUploader
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  def save_notification_message!(current_user, message_id, receiver_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      visitor_id: current_user.id,
      message_id: message_id,
      visited_id: receiver_id,
      action: 'message'
    )
    
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :index,:update,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def new
    @user = User.new
  end
  
  def create
    p params
    @user = User.new(user_params)
    @user.answer_digest = BCrypt::Password.create(params[:user][:answer_digest])
    if @user.save
      log_in @user
      remember(@user)
      flash[:success] = "登録が完了しました"
      redirect_to p_index_path
    else
      render :new
    end
  end
  
  def show
    p'show============'
    @user = User.find(params[:id])
    p'show_end=========='
    @posts = Kaminari.paginate_array(@user.posts).page(params[:page]).per(10)
  end
  
  def index
    @admin = User.find(1)
    @users = User.order("RANDOM()").all
    # @users = User.all
    @users = Kaminari.paginate_array(@users).page(params[:page])
  end
  
  def edit
    @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to u_show_path(current_user.id)
    else
      render 'edit'
    end
  end
  
  def status
    @user = User.find(params[:id])
    @users = @user.following
    @like_users = Kaminari.paginate_array(@users).page(params[:page]).per(5)
    @like_posts = Kaminari.paginate_array(@user.liked_posts).page(params[:page]).per(5)
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    # .paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    # .paginate(page: params[:page])
    render 'show_follow'
  end
  
  def destroy
    p params
    user = User.find_by(id: params[:id])
    user.destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  private
    def user_params
      params.require(:user).permit(:nickname, :age, :sex, :prefucture,
                                   :city, :classification, :nursing, :status,
                                   :key_word1, :key_word2, :key_word3,
                                   :answer_digest, :profile_image)
    end
    
    def correct_user
      @user = User.find(current_user.id)
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <a><%= f.submit "#{@user.nickname}さんをお気に入り登録", class: "sns-btn", style: "padding:10px 18px;" %></a>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <a><%= f.submit "#{@user.nickname}さんをお気入り解除", class: "sns-btn", style: "padding:10px 18px;" %></a>
<% end %>

app/views/users/edit.html.erb
<div class="container" style="margin-top: 15px">
  <h3 class="title">登録内容の変更</h3>
    <%= form_for(@user, url: u_up_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <div class="form-group">
        <%= f.label :nickname, value="ニックネーム（アプリに表示される名前）" %>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <label>年代</label><br>
        <label><%= f.radio_button :age, "10s" %>10代</label>
        <label><%= f.radio_button :age, "20s" %>20代</label>
        <label><%= f.radio_button :age, "30s" %>30代</label>
        <label><%= f.radio_button :age, "40s" %>40代</label>
        <label><%= f.radio_button :age, "50s" %>50代</label>
        <label><%= f.radio_button :age, "60s" %>60代</label>
        <label><%= f.radio_button :age, "70s" %>70代</label>
        <label><%= f.radio_button :age, "80s" %>80代</label>
        <label><%= f.radio_button :age, "90s" %>90代</label>
      </div>
      
      <div class="form-group">
        <label>性別</label>
        <br>
        <label><%= f.radio_button :sex, "men" %>男性</label>
        <label><%= f.radio_button :sex, "fimale" %>女性</label>
      </div>
      
      <div class="form-group">
        <%= f.label :prefucture, value="住所（都道府県）" %>
        <%= f.text_field :prefucture, id: 'pref', class: 'form-control', placeholder: '郵便番号から自動入力' %>
      </div>
      
      <div class="form-group">
        <%= f.label :city, value="住所（市町村）" %>
        <%= f.text_field :city, id: 'city', class: 'form-control', placeholder: '郵便番号から自動入力' %>
      </div>
      
      <div class="form-group">
        <label>分類</label><br>
        <label><%= f.radio_button :classification, "介護者" %>介護者</label>
        <label><%= f.radio_button :classification, "被介護者" %>被介護者</label>
        <label><%= f.radio_button :classification, "医療職" %>医療職</label>
      </div>
      
      <div class="form-group">
        <label>介護の対象</label><br>
        <label><%= f.radio_button :nursing, "実父" %>実父</label>
        <label><%= f.radio_button :nursing, "実母" %>実母</label>
        <label><%= f.radio_button :nursing, "義父" %>義父</label>
        <label><%= f.radio_button :nursing, "義母" %>義母</label>
        <label><%= f.radio_button :nursing, "祖父" %>祖父</label>
        <label><%= f.radio_button :nursing, "祖母" %>祖母</label>
        <label><%= f.radio_button :nursing, "兄弟姉妹" %>兄弟姉妹</label>
        <label><%= f.radio_button :nursing, "親戚" %>親戚</label>
        <label><%= f.radio_button :nursing, "その他" %>その他</label>
        <label><%= f.radio_button :nursing, "なし" %>なし</label>
      </div>
      
      <div class="form-group">
        <%= f.label :status, value="現状（プロフィール）" %>
        <%= f.text_area :status, class: 'form-control', rows: "5" %>
      </div>
      
      <div class="form-group">
        <%= f.label :key_word1, value="情報交換したい項目" %>
        <%= f.text_field :key_word1, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :key_word2, value="情報交換したい項目" %>
        <%= f.text_field :key_word2, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :key_word3, value="情報交換したい項目" %>
        <%= f.text_field :key_word3, class: 'form-control' %>
      </div>
      
      <div id="prf-pic">
        <%= f.label :profile_image, value="プロフィール画像の変更"%>
        <br>
        <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png' %>
        <div class="balloon1-top">
          <p>プロフィール画像を設定していない場合や
          <br>変更したい場合は画像を選択してください</p>
        </div>
      </div>
      <br>
      <br>
      
      <div style="text-align:center;">
      <%= f.submit "プロフィールを更新します", class: "btn1" %>
      </div>
    <% end %>
</div>

<script>
  $("#prf-pic").each(function() {
  $(this).hover(
      function() {
          $(this).children(".balloon1-top").fadeIn();
      },
      function() {
          $(this).children(".balloon1-top").fadeOut();
      }
  );
});
</script>

app/views/users/index.html.erb
<div class="container" style="margin-top: 15px">
  <h3 class="title">ユーザー一覧</h3>
    <% @users.each do |user| %>
      <% if user != current_user && user != @admin %>
        <div class="card space">
          <div class="card-header">
            <% if user.profile_image? %>
              <%= image_tag user.profile_image.url, class: "rounded-circle", size: "30x30" %>
            <% else %>
              <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
            <% end %>
            <%= link_to user.nickname, u_show_path(user.id) %>
          </div>
          <div class="card-body">
            <b>年代：</b><%= user.age %> <span class="space2"><b>性別：</b><%= user.sex %></span>
            <br>
            <b>居住エリア：</b><%= user.prefucture %>
            <br>
            <b>分類：</b><%= user.classification %>
            <br>
            <b>情報交換キーワード：</b>
            <br>
            <%= "#1.#{user.key_word1}" %>&emsp; <%= "#2.#{user.key_word2}" %>&emsp; <%= "#3.#{user.key_word3}" %>&emsp;
            <br>
          </div>
        </div>
        <% if current_user.admin? && !current_user?(user) %>
          <%= link_to "ユーザー削除", u_des_path(user.id), method: :delete,
                                      data: { confirm: "本当に削除しますか?" } %>
        <% end %>
      <% end %>
    <% end %>
    
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<div class="container" style="margin-top: 15px">
  <%= form_for(@user, url: u_create_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group" id="nickname">
      <b><%= f.label :nickname, value="ニックネーム" %></b>
      <%= f.text_field :nickname, class: 'form-control', placeholder: "アプリに表示される名前です" %>
      <!--<p class="popup">アプリに表示されるユーザーネームです</p>-->
    </div>
    
    <div class="form-group">
      <b><label>年代</label></b><br>
      <label><%= f.radio_button :age, "10歳代" %>10歳代</label>
      <label><%= f.radio_button :age, "20歳代" %>20歳代</label>
      <label><%= f.radio_button :age, "30歳代" %>30歳代</label>
      <label><%= f.radio_button :age, "40歳代" %>40歳代</label>
      <label><%= f.radio_button :age, "50歳代" %>50歳代</label>
      <label><%= f.radio_button :age, "60歳代" %>60歳代</label>
      <label><%= f.radio_button :age, "70歳代" %>70歳代</label>
      <label><%= f.radio_button :age, "80歳代" %>80歳代</label>
      <label><%= f.radio_button :age, "90歳代" %>90歳代</label>
    </div>
    
    <div class="form-group">
      <b><label>性別</label></b>
      <br>
      <label><%= f.radio_button :sex, "男性" %>男性</label>
      <label><%= f.radio_button :sex, "女性" %>女性</label>
    </div>
    
    <div class="form-group" id="address">
      <b><label>居住エリア（郵便番号から検索）</label></b>
      <br>
      <input type="text" id="postcode" maxlength="8" placeholder="例:0000000 「-」不要">
      <button id="btn">入力</button>
      <br>
      <div class="balloon1-top" style="width:200px;">
      <p>住所が自動入力されます</p>
      </div>
    </div>
    
    <div class="form-group hide open">
      <b><%= f.label :prefucture, value="住所（都道府県）" %></b>
      <%= f.text_field :prefucture, id: 'pref', class: 'form-control', placeholder: '郵便番号から自動入力' %>
    </div>
    
    <div class="form-group hide open">
      <b><%= f.label :city, value="住所（市区町村）" %></b>
      <%= f.text_field :city, id: 'city', class: 'form-control', placeholder: '郵便番号から自動入力' %>
    </div>
    
    <div class="form-group">
      <b><label>分類</label></b><br>
      <label><%= f.radio_button :classification, "介護者" %>介護者</label>
      <label><%= f.radio_button :classification, "被介護者" %>被介護者</label>
      <label><%= f.radio_button :classification, "医療職" %>医療職</label>
    </div>
    
    <div class="form-group">
      <b><label>介護の対象</label></b><br>
      <label><%= f.radio_button :nursing, "実父" %>実父</label>
      <label><%= f.radio_button :nursing, "実母" %>実母</label>
      <label><%= f.radio_button :nursing, "義父" %>義父</label>
      <label><%= f.radio_button :nursing, "義母" %>義母</label>
      <label><%= f.radio_button :nursing, "祖父" %>祖父</label>
      <label><%= f.radio_button :nursing, "祖母" %>祖母</label>
      <label><%= f.radio_button :nursing, "兄弟姉妹" %>兄弟姉妹</label>
      <label><%= f.radio_button :nursing, "親戚" %>親戚</label>
      <label><%= f.radio_button :nursing, "その他" %>その他</label>
      <label><%= f.radio_button :nursing, "なし" %>なし</label>
    </div>
    
    <div class="form-group">
      <b><%= f.label :status, value="現状（プロフィール）" %></b>
      <%= f.text_area :status, class: 'form-control', rows: "5" %>
    </div>
    
    <div id="key_word">
      <div class="form-group">
        <b><%= f.label :key_word1, value="情報交換したい項目１" %></b>
        <%= f.text_field :key_word1, class: 'form-control', placeholder: "例：認知症" %>
      </div>
      
      <div class="form-group">
        <b><%= f.label :key_word2, value="情報交換したい項目２" %></b>
        <%= f.text_field :key_word2, class: 'form-control', placeholder: "例：介護疲れ" %>
      </div>
      
      <div class="form-group">
        <b><%= f.label :key_word3, value="情報交換したい項目３" %></b>
        <%= f.text_field :key_word3, class: 'form-control', placeholder: "例：難病" %>
      </div>
      
      <div class="balloon1-top">
        <p>
        あなたが情報交換したい内容を記載してください。
        <br>
        情報交換をしやすくする検索ワードです。
        <br>
        項目1は必ず入力してください
        </p>
      </div>
    </div>
  
    <div class="form-group" id="answer">
      <b><%= f.label :answer_digest, value="好きな食べ物" %></b>
      <%= f.text_field :answer_digest, class: 'form-control', placeholder: "※ログインに必要な質問の答え " %>
      <div class="balloon1-top">
        <p>ログイン時の質問の答えは漢字やカタカナ、
        半角文字など上記の記載に完全に一致するようにしてください。</p>
      </div>
    </div>
    
    <b><%= f.label :profile_image, value="プロフィール画像"%></b>
    <br>
    <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png' %>
    
    <!--<%= f.file_field :profile_image, value: 'icon.png', class: 'hide', accept: 'image/jpeg,image/gif,image/png' %>-->
    <br>
    <br>
    
    <div style="text-align:center;" id="sign">
      <%= f.submit "新規登録", class: "btn1" %>
      <div class="balloon1-top">
        <p>登録内容はいつでもメニューの登録情報の更新から変更できます。</p>
      </div>
    </div>
    
  <% end %>
</div>

<script>

$(function(){
  $('#btn').on('click', () => {
    event.preventDefault();
    $('.open').fadeIn();
    $.ajax({
      url: "https://zipcloud.ibsnet.co.jp/api/search?zipcode=" + $('#postcode').val(),
      dataType: 'jsonp',
    }).done((data) => {
      if (data.results) { 
        getData(data.results[0]);
      } else {
        alert('該当データが見つかりません');
      }
    }).fail((data) => {
      alert('通信に失敗しました');
    });
  });

  function getData(data) {
    $('#pref').val(data.address1);
    $('#city').val(data.address2);
  }
});

$("#address").each(function() {
  $(this).hover(
      function() {
          $(this).children(".balloon1-top").fadeIn();
      },
      function() {
          $(this).children(".balloon1-top").fadeOut();
      }
  );
});

$("#key_word").each(function() {
  $(this).hover(
      function() {
          $(this).children(".balloon1-top").fadeIn();
      },
      function() {
          $(this).children(".balloon1-top").fadeOut();
      }
  );
});

$("#answer").each(function() {
  $(this).hover(
      function() {
          $(this).children(".balloon1-top").fadeIn();
      },
      function() {
          $(this).children(".balloon1-top").fadeOut();
      }
  );
});

$("#sign").each(function() {
  $(this).hover(
      function() {
          $(this).children(".balloon1-top").fadeIn();
      },
      function() {
          $(this).children(".balloon1-top").fadeOut();
      }
  );
});

</script>

app/views/users/show.html.erb
<div class="container" style="margin-top: 15px">
  <h3 class="title"><%= @user.nickname %></h3>
    <p class="title">さんのページ</p>
  
  <div class="prof">
    <div class="prof-icon">
      <% if @user.profile_image? %>
        <%= image_tag @user.profile_image.url, class: "rounded-circle", size: "130x130" %>
      <% else %>
        <%= image_tag "icon.png", class: "rounded-circle", size: "130x130", style: "border: 3px solid black;" %>
        <!--<i class="fas fa-user fa-5x" style="width:150px; height: auto; border-radius:50%;"></i>-->
      <% end %>
    </div>
      <div class="status">
        <p>
        <span class="align">年&emsp;代：</span><%= @user.age %>
        <br>
        <span class="align">性&emsp;別：</span><%= @user.sex %>
        <br>
        <span class="align">居住地：</span><%= @user.prefucture %>
        <br>
        <span class="align">分&emsp;類：</span><%= @user.classification %>
        <br>
        <span class="align">介護の対象：</span><%= @user.nursing %>
        </p>
      </div>
  </div>
  <hr>
  <div class="pfof-text">
    <h3 class="title">自己紹介</h3>
    <p><%= @user.status %></p>
    <hr>
    <div class="title">
      <h3>情報交換したいこと</h3>
      1.<%= @user.key_word1 %>,&emsp; 2.<%= @user.key_word2 %>,&emsp; 3.<%= @user.key_word3 %>
    </div>
    <hr>
  </div>
  <div class="sns-zone">
    <button class="sns-btn" style="padding:10px 18px;"><%= link_to "#{@user.nickname}さんのお気に入り一覧", u_sts_path("#{@user.id}") %></button>
    <%= render 'follow_form' if logged_in? %>
    <% unless current_user == @user %>
      <button class="sns-btn"><%= link_to "#{@user.nickname}さんにメッセージを送る", chat_path(sender_id: current_user.id, receiver_id: @user.id) %></button>
    <% end %>
    <!--<%= render 'shared/stats' %>-->
  </div>
<hr>
<h3 class="title">投稿一覧(全<%= @user.posts.count %>投稿）</h3>
  
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-header">
        <%= link_to post.title, p_show_path(post.id) %>
      </div>
      <div class="card-body">
        検索キーワード
        <br>
        <%= "#1.#{post.key_word1}" %>&emsp; <%= "#2.#{post.key_word2}" %>&emsp; <%= "#3.#{post.key_word3}" %>&emsp;
        <%= "#4.#{post.key_word4}" %>&emsp; <%= "#5.#{post.key_word5}" %>&emsp;
        <br>
        <br>
        <%= "投稿時間：#{post.created_at.to_s(:datetime_jp)}" %>
        <br>
      </div>
    </div>
  <% end %>
  <%= paginate @posts %>
  </div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.nickname %></h1>
      <span><%= link_to "マイページ", @user %></span>
      <span><b>投稿数:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <% user.nickname %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users %>
      <ul class="users follow">
        <% @users.each do |user| %>
            <% user.nickname %>
          <% end %>
      </ul>
    <% end %>
  </div>
</div>