config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_like',      to: 'posts#like',   as: 'p_like'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  delete 'pic1_delete/:id',    to: 'posts#pic_des1', as: 'pic1_des'
  delete 'pic2_delete/:id',    to: 'posts#pic_des2', as: 'pic2_des'
  delete 'pic3_delete/:id',    to: 'posts#pic_des3', as: 'pic3_des'
  delete 'pic4_delete/:id',    to: 'posts#pic_des4', as: 'pic4_des'
  delete 'pic5_delete/:id',    to: 'posts#pic_des5', as: 'pic5_des'
  delete 'mov_delete/:id',     to: 'posts#mov_des',  as: 'mov_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  delete 'comment_delete/:id',    to: 'comments#destroy', as: 'com_des'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  delete 'reply_delete/:id',    to: 'replies#destroy', as: 'rep_des'
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',  to: 'users#show',   as: 'u_show'
  get  'user/status/:id',    to: 'users#status',  as: 'u_sts'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get    '/login',         to: 'sessions#new',       as: 'login'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/edit',          to: 'sessions#edit',      as: 're_log'
  patch  '/update/login',        to: 'sessions#update',    as: 'log_upd'

  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  delete 'room_delete/:id',            to: 'rooms#destroy', as: 'room_des'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
  delete 'message_delete/:id',         to: 'messages#destroy', as: 'mes_des'
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'result', to: 'search#result'
  
  resources :notifications, only: :index
  
  delete 'user_delete/:id', to: 'users#destroy', as: 'u_des'
  
  get  'consultation',      to: 'consultations#new',   as: 'consultation'
  post 'consultation_send', to: 'consultations#create',  as: 'cons_create'
  get  'acceptance',        to: 'consultations#accep', as: 'accep'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    if params[:nickname].present?
      @users = User.where('nickname LIKE ?', "%#{params[:nickname]}%")
    else
      # flash.now[:alert] = "検索ワードを入力してください"
      @users = User.none
    end
    @user = current_user
    @rooms = Room.where(sender_id: @user.id).or(Room.where(receiver_id: @user.id))
  end
  
  def chat
    @sender = current_user
    p '1==========='
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
    p '2============'
      @room = room_check(@sender, @receiver)
    end
    if params[:room_id]
    p '3==============='
      @room = Room.find_by(id: params[:room_id])
    end
    if @room
      p "========="
      p @room.id
      p "========="
      @messages = Message.where(room_id: @room.id)
    end
  end
  
  def destroy
    p params
    room = Room.find_by(id: params[:id])
    room.destroy
    flash[:success] = "メッセージ履歴を削除しました"
    redirect_back(fallback_location: root_path)
  end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/chat.html.erb
<h3 class="title">
  <% if @room %>
    <% if @room.receiver.id == current_user.id %>
      <%= @room.sender.nickname %><br>さんとのメッセージ
    <% else %>
      <%= @room.receiver.nickname %><br>さんとのメッセージ
    <% end %>
  <% else %>
    <%= @receiver.nickname %><br>さんとのメッセージ
  <% end %>
</h3>

  <% @messages&.each do |message| %>
    <div class="kaiwa line">
      <% if message.sender_id == current_user.id %>
        <div class="nameright">
          <%= @sender.nickname %>
        </div>
        <div class="fukidasi right">
          <% if @sender.profile_image? %>
            <%= image_tag @sender.profile_image.url, width: "40px", class: "iconright" %>
          <% else %>
            <i class="iconright fas fa-user fa-2x"></i>
          <% end %>
          <%= message.content %>
        </div>
        <div class="mes_des">
          <% if current_user.id == message.sender_id %>
            <%= link_to "削除", mes_des_path(message.id), method: :delete %>
          <% end %>
        </div>
        <br>
    <% else %>
      <% if @room.receiver == current_user %>
        <% @receiver = @room.sender %>
      <% else %>
        <% @receiver = @room.receiver %>
      <% end %>
        <div class="name">
          <%= @receiver.nickname %>
        </div>
        <div class="fukidasi left">
          <% if @receiver.profile_image? %>
            <%= image_tag @receiver.profile_image.url, width: "40px", class: "icon" %>
          <% else %>
            <i class="icon fas fa-user fa-2x"></i>
          <% end %>
          <%= message.content %>
        </div>
        <br>
        <br>
        <% if current_user.id == message.sender_id %>
          <%= link_to "削除", mes_des_path(message.id), method: :delete %>
        <% end %>
      <% end %>
     </div>
  <% end %>

<div class="form-fix">
<div class="mes-form">
  <%= form_for(:message, url: m_send_path) do |form| %>
    <%= form.text_area :content, id: "content", rows: "3", class: "form_textarea", style: "width:83%" %>
    <% if @room %>
      <%= form.text_field :room_id, class: "hidden hide", value: @room.id %>
    <% else %>
      <%= form.text_field :sender_id, class: "hidden hide", value: @sender.id %>
      <%= form.text_field :receiver_id, class: "hidden hide", value: @receiver.id %>
    <% end %>
    <br>
    <%= form.submit "メッセージ送信", class: "mes-btn" %>
  <% end %>
</div>
</div>

app/views/rooms/index.html.erb
<h3 class="title">メッセージルーム</h3>

  <h4 class="title">メッセージ履歴</h4>
      <% @rooms.each do | room | %>
        <div class="card">
          <div class="card-header">
            <% if @user.id == room.receiver.id %>
              <% if room.sender.profile_image? %>
                <%= image_tag room.sender.profile_image.url, class: "rounded-circle", size: "30x30" %>
                <%= link_to "#{room.sender.nickname}さんとのメッセージ", exist_room_path(room.id) %>
              <% else %>
                <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
                <%= link_to "#{room.sender.nickname}さんとのメッセージ", exist_room_path(room.id) %>
              <% end %>
            <% else %>
              <% if room.sender.profile_image? %>
                <%= image_tag room.receiver.profile_image.url, class: "rounded-circle", size: "30x30" %>
                <%= link_to "#{room.receiver.nickname}さんとのメッセージ", exist_room_path(room.id) %>
              <% else %>
                <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
                <%= link_to "#{room.receiver.nickname}さんとのメッセージ", exist_room_path(room.id) %>
              <% end %>
            <% end %>
            <br>
            <div class="posi-r">
              <%= link_to "履歴の削除", room_des_path(room.id), method: :delete %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @rooms.empty? %>
        <b><p class="title" style="margin-top:8%;">メッセージの履歴がありません</p></b>
      <% end %>
 
  <hr style="margin:30px 0px;">
  
  <h4 class="title">ユーザー検索</h4>
    <div id="u_search" class="s_window">
      <input type="text" name="nickname" placeholder="ニックネームを入力" id="nickname" oninput="input_check()"/>
      <button id="search_nickname" disabled>検索</button>
      <div id="nickname_result"></div>
    </div>
 

<script>
function input_check(){
  let nickname = document.getElementById("nickname").value.length;
  
  if(nickname >= 1){
    document.getElementById("search_nickname").removeAttribute("disabled");
  }else{
    document.getElementById("search_nickname").setAttribute("disabled", true);
  }
}

$(document).on('turbolinks:load', (function(){
      $('#search_nickname').click(function(){
        let nickname = $('#nickname').val();
        $.ajax({
          type: 'GET',
          url: '/result',
          data: {nickname: nickname},
          dataType: 'json'
        })
        .done(function(data){
          nic_check(data.users)
        　
        　$.each(data.users, function(index,val){
            $('.result').append(
              (nic_result(val))
            )
          })
          console.log(data.users);
        })
      })
    }))
    
var nic_check = (data) => {
    if (data.length === 0) {
      $('#nickname_p').remove()
      $('.result').remove()
      $('#nickname_result').append('<p id="nickname_p" style="margin-top:16px;">ニックネーム検索結果<br><br><b>一致する検索結果がありませんでした</b></p>');
    } else {
      $('#nickname_p').remove()
      $('.result').remove()
      $('#nickname_result').append('<p id="nickname_p" style="margin-top:16px;">ニックネーム検索結果</p>');
      $('#nickname_result').append('<div class="result"></div>');
    }
  }
  
var nic_result = (val) => {
    console.log(val)
    if (val !== null && val.id !== 1){
    return $('<div class="card" style="margin-bottom:10px;">')
          .append(`<div class="card-header">${prof_pic(val)}</div>`)
          .append('</div>')
    } 
  }

var prof_pic = (val) => {
      console.log(val)
      if(val.profile_image.url !== null){
        return `<img src="${val.profile_image.url}" class="rounded-circle" width="30px" height="30px"><a href="user/show/${val.id}">${val.nickname}</a>`
      }else{
        return `<img src="/assets/icon.png" alt="写真なしのアイコン" class="rounded-circle" width="30px" height="30px"><a href="user/show/${val.id}">${val.nickname}</a>`
      }
    }
  
</script>