config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'post_new',       to: 'posts#new',    as: 'p_new'
  post 'post_create',    to: 'posts#create', as: 'p_create'
  get  'post_index',     to: 'posts#index',  as: 'p_index'
  get  'post_like',      to: 'posts#like',   as: 'p_like'
  get  'post_show/:id',  to: 'posts#show',   as: 'p_show'
  get  'post_edit/:id',  to: 'posts#edit',   as: 'p_edit'
  patch  'post_update/:id',    to: 'posts#update',  as: 'p_up'
  delete 'post_delete/:id',    to: 'posts#destroy', as: 'p_des'
  delete 'pic1_delete/:id',    to: 'posts#pic_des1', as: 'pic1_des'
  delete 'pic2_delete/:id',    to: 'posts#pic_des2', as: 'pic2_des'
  delete 'pic3_delete/:id',    to: 'posts#pic_des3', as: 'pic3_des'
  delete 'pic4_delete/:id',    to: 'posts#pic_des4', as: 'pic4_des'
  delete 'pic5_delete/:id',    to: 'posts#pic_des5', as: 'pic5_des'
  delete 'mov_delete/:id',     to: 'posts#mov_des',  as: 'mov_des'
  post  'posts/:post_id/comment',    to: 'comments#create', as: 'p_com'
  delete 'comment_delete/:id',    to: 'comments#destroy', as: 'com_des'
  post  'posts/:user_id/comment/:comment_id', to: 'replies#create', as: 'reply'
  delete 'reply_delete/:id',    to: 'replies#destroy', as: 'rep_des'
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :relationships,       only: [:create, :destroy]
  
  get  'user/new',       to: 'users#new',    as: 'u_new'
  post 'user/create',    to: 'users#create', as: 'u_create'
  get  'user/index',     to: 'users#index',  as: 'u_index'
  get  'user/show/:id',  to: 'users#show',   as: 'u_show'
  get  'user/status/:id',    to: 'users#status',  as: 'u_sts'
  get  'user/edit',      to: 'users#edit',   as: 'u_edit'
  patch'user/update',    to: 'users#update', as: 'u_up'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get    '/login',         to: 'sessions#new',       as: 'login'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/edit',          to: 'sessions#edit',      as: 're_log'
  patch  '/update/login',        to: 'sessions#update',    as: 'log_upd'

  get  'room/index/:id',               to: 'rooms#index',   as: 'room'
  get  'chat/:room_id',                to: 'rooms#chat',    as: 'exist_room'
  get  'chat/:sender_id/:receiver_id', to: 'rooms#chat',    as: 'chat'
  delete 'room_delete/:id',            to: 'rooms#destroy', as: 'room_des'
  post 'message/send',                 to: 'messages#sending', as: 'm_send'
  delete 'message_delete/:id',         to: 'messages#destroy', as: 'mes_des'
  
  get 'search_func', to: 'search#search',  as: 'search_func'
  get 'result', to: 'search#result'
  
  resources :notifications, only: :index
  
  delete 'user_delete/:id', to: 'users#destroy', as: 'u_des'
  
  get  'consultation',      to: 'consultations#new',   as: 'consultation'
  post 'consultation_send', to: 'consultations#create',  as: 'cons_create'
  get  'acceptance',        to: 'consultations#accep', as: 'accep'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :replies, class_name: 'Reply', foreign_key: :user_id, dependent: :destroy
    has_many :notifications, dependent: :destroy
    
    default_scope -> { order(created_at: :desc) }
    mount_uploader :picture1, PictureUploader
    mount_uploader :picture2, PictureUploader
    mount_uploader :picture3, PictureUploader
    mount_uploader :picture4, PictureUploader
    mount_uploader :picture5, PictureUploader
    mount_uploader :video, VideoUploader
    validates :title, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 255 }
    validates :key_word1, presence: { message: 'は１つは入力してください。' }
    validates :user_id, presence: true
    validate :picture_size1
    validate :picture_size2
    validate :picture_size3
    validate :picture_size4
    validate :picture_size5
    
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
    
    private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size1
      if picture1.size > 5.megabytes  
        errors.add(:picture1, "の容量が5MBを超えているため投稿できません。")
      end
    end
    
    def picture_size2
      if picture2.size > 5.megabytes  
        errors.add(:picture2, "の容量が5MBを超えているため投稿できません。")
      end
    end
    
    def picture_size3
      if picture3.size > 5.megabytes  
        errors.add(:picture3, "の容量が5MBを超えているため投稿できません。")
      end
    end
    
    def picture_size4
      if picture4.size > 5.megabytes  
        errors.add(:picture4, "の容量が5MBを超えているため投稿できません。")
      end
    end
    
    def picture_size5
      if picture5.size > 5.megabytes  
        errors.add(:picture5, "の容量が5MBを超えているため投稿できません。")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :index, :show]
  before_action :correct_user,   only: [:update, :destroy]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿成功しました"
      redirect_to p_index_path
    else
      render :new
    end
  end
  
  def index
    @posts = Post.order("RANDOM()").all
    @posts = Kaminari.paginate_array(@posts).page(params[:page])
  end
  
  def like
    @user = current_user
    @follow_users = @user.following
    # @follow_users.each do |fu|
    #   fu.posts.each do |lp|
    #     @posts = Kaminari.paginate_array(lp).page(params[:page]).per(10)
    #   end
    # end
  end
  
  def show
    p 'show_start========================='
    @post = Post.find(params[:id])
    @like = Like.new
    @comments = @post.comments
    @comment = Comment.new
    @reply = Reply.new
    p 'end========================='
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "投稿内容を更新しました"
      redirect_to p_show_path
    else
      render :edit
    end
  end
  
  def destroy
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to u_show_path(current_user)
    p 'des_end========================='
  end
  
  def pic_des1
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.remove_picture1!
    @post.save
    flash[:success] = "写真１を削除しました"
    redirect_to p_edit_path(@post.id)
    p 'des_end========================='
  end
  
  def pic_des2
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.remove_picture2!
    @post.save
    flash[:success] = "写真２を削除しました"
    redirect_to p_edit_path(@post.id)
    p 'des_end========================='
  end
  
  def pic_des3
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.remove_picture3!
    @post.save
    flash[:success] = "写真３を削除しました"
    redirect_to p_edit_path(@post.id)
    p 'des_end========================='
  end
  
  def pic_des4
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.remove_picture4!
    @post.save
    flash[:success] = "写真４を削除しました"
    redirect_to p_edit_path(@post.id)
    p 'des_end========================='
  end
  
  def pic_des5
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.remove_picture5!
    @post.save
    flash[:success] = "写真５を削除しました"
    redirect_to p_edit_path(@post.id)
    p 'des_end========================='
  end
  
  def mov_des
    p 'des_start========================='
    @post = Post.find_by(id: params[:id])
    @post.remove_video!
    @post.save
    flash[:success] = "動画を削除しました"
    redirect_to p_edit_path(@post.id)
    p 'des_end========================='
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :picture1, :picture2,
                                   :picture3, :picture4, :picture5, :video,
                                   :key_word1, :key_word2, :key_word3, :key_word4,
                                   :key_word5)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container" style="margin-top: 15px">
  <h3 class="title">投稿の編集</h1>
    <%= form_for(@post, url: p_up_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control', rows: "10" %>
        
        <%= f.label :key_word1, value="検索キーワード1"%>
        <%= f.text_field :key_word1, class: 'form-control' %>
        
        <%= f.label :key_word2, value="検索キーワード2"%>
        <%= f.text_field :key_word2, class: 'form-control' %>
        
        <%= f.label :key_word3, value="検索キーワード3"%>
        <%= f.text_field :key_word3, class: 'form-control' %>
        
        <%= f.label :key_word4, value="検索キーワード4"%>
        <%= f.text_field :key_word4, class: 'form-control' %>
        
        <%= f.label :key_word5, value="検索キーワード5"%>
        <%= f.text_field :key_word5, class: 'form-control' %>
        
        <div style="margin:25px 0px;"></div>
        
        <div id="pic-mov">
        <span class="picture">
          <div class="pic-box">
            <div class="pic-box-item">
              <p>写真１</p>
              <div class="pic-border">
                <% if @post.picture1? %>
                  <%= image_tag(@post.picture1.url, class: "resize2") %>
                <% else %>
                  <p>写真１なし</p>
                <% end %>
              </div>
              <% if @post.picture1? %>
                <p><%= link_to "写真１の削除", pic1_des_path(@post.id), method: :delete %></p>
              <% end %>
            </div>
            <div class="pic-box-item">
              <p>写真２</p>
              <div class="pic-border">
                <% if @post.picture2? %>
                  <%= image_tag(@post.picture2.url, class: "resize2") %>
                <% else %>
                  <p>写真２なし</p>
                <% end %>
              </div>
              <% if @post.picture2? %>
                <p><%= link_to "写真２の削除", pic2_des_path(@post.id), method: :delete %></p>
              <% end %>
            </div>
            <div class="pic-box-item">
              <p>写真３</p>
              <div class="pic-border">
                <% if @post.picture3? %>
                  <%= image_tag(@post.picture3.url, class: "resize2") %>
                <% else %>
                  <p>写真３なし</p>
                <% end %>
              </div>
              <% if @post.picture3? %>
                <p><%= link_to "写真３の削除", pic3_des_path(@post.id), method: :delete %></p>
              <% end %>
            </div>
          </div>
          
          <div class="pic-box">
            <div class="pic-box-item">
              <p>写真４</p>
              <div class="pic-border">
                <% if @post.picture4? %>
                  <%= image_tag(@post.picture4.url, class: "resize2") %>
                <% else %>
                  <p>写真４なし</p>
                <% end %>
              </div>
              <% if @post.picture4? %>
                <p><%= link_to "写真４の削除", pic4_des_path(@post.id), method: :delete %></p>
              <% end %>
            </div>
            <div class="pic-box-item">
              <p>写真５</p>
              <div class="pic-border">
                <% if @post.picture5? %>
                  <%= image_tag(@post.picture5.url, class: "resize2") %>
                <% else %>
                  <p>写真５なし</p>
                <% end %>
              </div>
              <% if @post.picture5? %>
                <p><%= link_to "写真５の削除", pic5_des_path(@post.id), method: :delete %></p>
              <% end %>
            </div>
            <div class="pic-box-item">
              <p>動画</p>
              <div class="pic-border">
                <% if @post.video? %>
                  <%= link_to @post.video_url.to_s do %>
                    <%= video_tag(@post.video.to_s, class: "resize2") %>
                  <% end %>
                <% else %>
                  <p>動画なし</p>
                <% end %>
              </div>
              <% if @post.video? %>
                <p><%= link_to "動画の削除", mov_des_path(@post.id), method: :delete %></p>
              <% end %>
            </div>
          </div>
          <br>
         <%= f.label :"写真１を追加もしくは変更する" %>
         <br>
         <%= f.file_field :picture1, accept: 'image/jpeg,image/gif,image/png' %>
         <br>
         <br>
         <%= f.label :"写真２を追加もしくは変更する" %>
         <br>
         <%= f.file_field :picture2, accept: 'image/jpeg,image/gif,image/png' %>
         <br>
         <br>
         <%= f.label :"写真３を追加もしくは変更する" %>
         <br>
         <%= f.file_field :picture3, accept: 'image/jpeg,image/gif,image/png' %>
         <br>
         <br>
         <%= f.label :"写真４を追加もしくは変更する" %>
         <br>
         <%= f.file_field :picture4, accept: 'image/jpeg,image/gif,image/png' %>
         <br>
         <br>
         <%= f.label :"写真５を追加もしくは変更する" %>
         <br>
         <%= f.file_field :picture5, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
        
        <div style="margin:25px 0px;"></div>
        <span class="video">
         <%= f.label :"動画を追加もしくは変更する" %>
         <br>
         <%= f.file_field :video, :accept => 'video/*' %>
        </span>
        <div class="balloon1-top">
          <p>投稿時の表示は写真１～５の順で、最後に動画が表示されます。
          <br>写真は1枚あたり容量5MB以下までしか投稿できません。
          </p>
        </div>
        </div>
        
        <!--<div style="margin:25px 0px;"></div>-->
        <div style="text-align:center; margin:25px 0px;">
          <%= f.submit "編集", class: "btn1" %>
        </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container" style="margin-top: 15px">
  <h3 class="title">投稿一覧</h1>
    <% @posts.each do |post| %>
      
        <div class="card">
          <div class="card-header">
            <% if post.user.profile_image? %>
              <%= image_tag post.user.profile_image.url, class: "rounded-circle", size: "30x30" %>
            <% else %>
              <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
            <% end %>
            <%= link_to post.user.nickname, u_show_path(post.user.id) %>
          </div>
          <div class="card-body">
            <b>タイトル：</b><%= link_to post.title, p_show_path(post.id) %>
            <br>
            <br>
            <b>検索キーワード：</b>
            <br>
            <%= "#1.#{post.key_word1}" %>&emsp; <%= "#2.#{post.key_word2}" %>&emsp; <%= "#3.#{post.key_word3}" %>&emsp;
            <%= "#4.#{post.key_word4}" %>&emsp; <%= "#5.#{post.key_word5}" %>&emsp;
            <br>
            <br>
            <b>投稿日時：</b><%= post.created_at.to_s(:datetime_jp) %>
            <br>
          </div>
        </div>
      
    <% end %>

<%= paginate @posts %>
</div>

app/views/posts/like.html.erb
<div class="container" style="margin-top: 15px">
  <h3 class="title">お気に入りユーザーの
  <br>投稿一覧</h3>

    
  <% @follow_users.each do |fu| %>
    <% fu.posts.each do |lp| %>
      <div class="card">
        <div class="card-header">
          <% if fu.profile_image? %>
            <%= image_tag fu.profile_image.url, class: "rounded-circle", size: "30x30" %>
          <% else %>
            <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
          <% end %>
          <%= link_to fu.nickname, u_show_path(fu.id) %>
        </div>
        <div class="card-body">
          <b>タイトル：</b><%= link_to lp.title, p_show_path(lp.id) %>
          <br>
          <br>
          <b>検索キーワード：</b>
          <br>
          <%= "#1.#{lp.key_word1}" %>&emsp; <%= "#2.#{lp.key_word2}" %>&emsp; <%= "#3.#{lp.key_word3}" %>&emsp;
          <%= "#4.#{lp.key_word4}" %>&emsp; <%= "#5.#{lp.key_word5}" %>&emsp;
          <br>
          <br>
          <b>投稿日時：</b><%= lp.created_at.to_s(:datetime_jp) %>
          <br>
        </div>
      </div>
    <% end %>
    <% if fu.posts == [] %>
      ※まだ<%= link_to fu.nickname, u_show_path(fu.id) %> さんの
      <br>&emsp;投稿はありません
      <br>
      <br>
    <% end %>
  <% end %>
  <% if @follow_users == [] %>
    <p style="margin-top:10%; text-align:center;">まだお気に入り登録している
    <br>ユーザーがいません</p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container" style="margin-top: 15px">
  <div class="card">
    <div class="card-header">
      <% if @post.user.profile_image? %>
            <%= image_tag @post.user.profile_image.url, class: "rounded-circle", size: "30x30" %>
          <% else %>
            <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
            <!--<i class="fas fa-user fa-3x"></i>-->
          <% end %>
      <%= link_to @post.user.nickname, u_show_path(@post.user.id) %>
    </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0 title">
      <div class="swiper-container">
      	<div class="swiper-wrapper">
      		<% if @post.picture1? %>
      		  <div class="swiper-slide"><%= image_tag @post.picture1.url, class: "resize" %></div>
      		<% end %>
      		<%  if @post.picture2? %>
      		  <div class="swiper-slide"><%= image_tag @post.picture2.url, class: "resize" %></div>
      		<% end %>
      		<%  if @post.picture3? %>
      		  <div class="swiper-slide"><%= image_tag @post.picture3.url, class: "resize" %></div>
      		<% end %>
      		<%  if @post.picture4? %>
      		  <div class="swiper-slide"><%= image_tag @post.picture4.url, class: "resize" %></div>
      	  <% end %>
      	  <%  if @post.picture5? %>
      	    <div class="swiper-slide"><%= image_tag @post.picture5.url, class: "resize" %></div>
      		<% end %>
      		<%  if @post.video? %>
      		  <div class="swiper-slide">
        		  <%= link_to @post.video_url.to_s do %>
                <%= video_tag @post.video.to_s, class: "resize", style: "width: 100%;" %>
              <% end %>
              ※動画：画面をタップして再生
            </div>
          <% end %>
      	</div>
	      <div class="swiper-pagination"></div>
      </div>
      <p style="text-align:left; margin-top:20px;"><%= @post.content %></p>
      <footer class="blockquote-footer" style="text-align:right;">作成時間: <i class="far fa-clock clock-icon"></i><%= date_format(@post.created_at) %></footer>
    </blockquote>
  </div>
    <% if current_user?(@post.user) %>
    <div class="edit_delete">
      <%= link_to "投稿の編集", p_edit_path(@post.id) %>
      <%= link_to "投稿の削除", p_des_path(@post.id), method: :delete %>
    </div>
    <% end %>
  </div>
    <button class="hide_btn">
    <% if current_user.already_liked?(@post) %>
      <a href="/posts/<%= @post.id %>/likes/<%= current_user.id%>" data-method="delete"><i class="fas fa-heart"></i>取り消し</a>
    <% else %>
      <a href="/posts/<%= @post.id %>/likes" data-method="post"><i class="far fa-heart"></i>お気に入り</a>
    <% end %>
    </button>
    <button id="comment" class="hide_btn" style="outline:none;"><a><i class="far fa-comments"></i>コメントする</a></button>
    <!--<a id="comment"><i class="far fa-comments"></i>コメントする</a>-->
    <div id="comment_form" class="card my-1"> 
      <div class="card-body">
        <p class="font-weight-bold">投稿へのコメント</p>
        <%= form_for(@comment, url: p_com_path(@post.id)) do |f| %>
          <div class="title">
            <%= f.text_area :content, rows:3, style: "width:90%;" %>
            <br>
            <%= f.submit 'コメントする', class: "btn1" %>
          </div>
        <% end %>
      </div>
    </div>
    
    <h3 class="title">コメント一覧</h3>
      <% if @comments.presence %>
        <% @comments.each do |c| %>
          <div class="card">
            <div class="card-header">
              <% if c.user.profile_image? %>
                <%= image_tag c.user.profile_image.url, class: "rounded-circle", size: "30x30" %>
              <% else %>
                <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
              <% end %>
              <%= link_to c.user.nickname, u_show_path(c.user.id) %>
            </div>
            <div class="card-body">
              <!--<b><%= "#{c.post.user.nickname}さんへ" %></b>-->
              <!--<br>-->
              <%= c.content %>
              <br>
              <br>
              <%= "コメント時間：#{date_format(c.created_at)}" %>
              <br>
              <% if current_user.id == c.user_id%>
                <%= link_to "コメントの削除", com_des_path(c.id), method: :delete %>
              <% end %>
            </div>
              <a href="#" class="reply">返信</a>
              <div class="reply_form">
                <%= form_for(@reply, url: reply_path(comment_id: c.id, user_id: current_user.id)) do |f| %>
                  <div class="title">
                    <%= f.text_area :re_comment, rows:3, style: "width:90%;" %>
                    <br>
                    <%= f.submit 'コメントに返信する', class: "btn1" %>
                  </div>
                <% end %>
              </div>
          </div>
                <% if c.replies.presence %>
                  <% c.replies.each do |rep| %>
                    <div class="card rep">
                      <div class="card-header">
                        <% if rep.user.profile_image? %>
                          <%= image_tag rep.user.profile_image.url, class: "rounded-circle", size: "30x30" %>
                        <% else %>
                          <%= image_tag "icon.png", class: "rounded-circle", size: "30x30", style: "border: 3px solid black;" %>
                        <% end %>
                        <%= link_to rep.user.nickname, u_show_path(rep.user.id) %>
                      </div>
                      <div class="card-body">
                        <%= rep.re_comment %>
                        <br>
                        <br>
                        <%= "コメント時間：#{date_format(rep.created_at)}" %>
                        <br>
                        <% if current_user.id == rep.user_id%>
                          <%= link_to "コメントの削除", rep_des_path(rep.id), method: :delete %>
                        <% end %>
                      </div>
                      <a href="#" class="reply">返信</a>
                        <div class="reply_form">
                          <%= form_for(@reply, url: reply_path(comment_id: c.id, user_id: current_user.id)) do |f| %>
                            <div class="title">
                              <%= f.text_area :re_comment, rows:3, style: "width:90%;" %>
                              <br>
                              <%= f.submit 'コメントに返信する', class: "btn1" %>
                            </div>
                          <% end %>
                        </div>
                    </div>
                  <% end %>
                <% end %>
        <% end %>
      <% else %>
        <p class="title">まだコメントがありません。</p>
      <% end %>
</div>



<script>
  $('#comment').click(function() {
        $('#comment_form').fadeIn();
    })
    
  document.querySelectorAll('.reply').forEach((el) => {
    el.addEventListener('click', (ev) => {
      ev.preventDefault();
      el.nextElementSibling.style = 'display: block;'
    })
  })
  
  var mySwiper = new Swiper('.swiper-container', {
      pagination: {
  		el: '.swiper-pagination',
  		type: 'bullets',
  		clickable: true
  	}
});
</script>